CLASS zbp_i_student_projects DEFINITION
    PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZI_STUDENT_PROJECTS .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zbp_i_student_projects IMPLEMENTATION.
ENDCLASS.
